//授权码模式oauth2，授权码模式适合客户端和认证服务非同一个系统的情况
### 通过code获取token令牌
POST {{auth_host}}/auth/oauth/token?client_id=XcWebApp&client_secret=XcWebApp&grant_type=authorization_code&code=N4BLbS&redirect_uri=http:###www.51xuecheng.cn



### 校验jwt令牌
POST {{auth_host}}/auth/oauth/check_token?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsieHVlY2hlbmctcGx1cyJdLCJ1c2VyX25hbWUiOiJ7XCJjb21wYW55SWRcIjpcIjEyMzIxNDE0MjVcIixcImNyZWF0ZVRpbWVcIjpcIjIwMjItMDktMjhUMDg6MzI6MDNcIixcImlkXCI6XCI1MlwiLFwibmFtZVwiOlwiTeiAgeW4iFwiLFwicGVybWlzc2lvbnNcIjpbXSxcInNleFwiOlwiMVwiLFwic3RhdHVzXCI6XCJcIixcInVzZXJuYW1lXCI6XCJ0MVwiLFwidXR5cGVcIjpcIjEwMTAwMlwifSIsInNjb3BlIjpbImFsbCJdLCJleHAiOjE3NDgyNTY0OTQsImF1dGhvcml0aWVzIjpbInhjX3RlYWNobWFuYWdlcl9jb3Vyc2VfYmFzZSIsInhjX3RlYWNobWFuYWdlcl9jb3Vyc2VfZGVsIiwieGNfdGVhY2htYW5hZ2VyX2NvdXJzZV9saXN0IiwieGNfdGVhY2htYW5hZ2VyX2NvdXJzZV9wbGFuIiwieGNfdGVhY2htYW5hZ2VyX2NvdXJzZSIsInhjX3RlYWNobWFuYWdlciIsInhjX3RlYWNobWFuYWdlcl9jb3Vyc2VfbWFya2V0IiwieGNfdGVhY2htYW5hZ2VyX2NvdXJzZV9wdWJsaXNoIiwieGNfdGVhY2htYW5hZ2VyX2NvdXJzZV9hZGQiXSwianRpIjoiNDhjYmU2MjktZGJlZS00YjMxLTgyYWYtNGFhZWU4YTc2NzRhIiwiY2xpZW50X2lkIjoiWGNXZWJBcHAifQ.9up8EsawfLIqfeDyx59QqeMHfhw5F7M4RNallLfJrho



### 测试课程资源携带token
GET {{auth_host}}/content/course/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsieHVlY2hlbmctcGx1cyJdLCJ1c2VyX25hbWUiOiJ7XCJiaXJ0aGRheVwiOlwiMjAyMi0wOS0yOFQxOToyODo0NlwiLFwiY3JlYXRlVGltZVwiOlwiMjAyMi0wOS0yOFQwODozMjowM1wiLFwiaWRcIjpcIjUwXCIsXCJuYW1lXCI6XCLlrabnlJ8xXCIsXCJuaWNrbmFtZVwiOlwi5aSn5rC054mbXCIsXCJzZXhcIjpcIjFcIixcInN0YXR1c1wiOlwiMVwiLFwidXNlcm5hbWVcIjpcInN0dTFcIixcInVzZXJwaWNcIjpcImh0dHA6Ly9maWxlLjUxeHVlY2hlbmcuY24vZGRkZlwiLFwidXR5cGVcIjpcIjEwMTAwMVwifSIsInNjb3BlIjpbImFsbCJdLCJleHAiOjE3NDgwMjI0OTEsImF1dGhvcml0aWVzIjpbInRlc3QiXSwianRpIjoiNjYxMGQxYjMtYzBhMi00ODMzLWJkOWMtMGRjNTA0ZDg0ODU5IiwiY2xpZW50X2lkIjoiWGNXZWJBcHAifQ.LxQaSpKWdNjkveHYr63gOO67SU2-i6Q48ScsPx2Dv70



###
GET {{gateway_host}}/content/course/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsieHVlY2hlbmctcGx1cyJdLCJ1c2VyX25hbWUiOiLlvKDkuIkiLCJzY29wZSI6WyJhbGwiXSwiZXhwIjoxNzQ3OTk3Mjc1LCJhdXRob3JpdGllcyI6WyJwMSJdLCJqdGkiOiJhY2EwZjdhYi03MDA5LTQxZjEtYTRhOC1lODM3ODJkNDE3ZWEiLCJjbGllbnRfaWQiOiJYY1dlYkFwcCJ9.cW852a6fNMqmX0e1hT434dhX4NPuhaIpYn9K44GtJcE



//##############扩展认证请求参数后######################
###post密码模式
POST {{gateway_host}}/auth/oauth/token
Content-Type: application/x-www-form-urlencoded

client_id=XcWebApp&client_secret=XcWebApp&grant_type=password&username={"username":"stu1","authType":"password","password":"111111"}


###账号注册
POST {{auth_host}}/auth/register
Content-Type: application/json

{
  "cellphone": "111111",
  "username": "gc",
  "email": "gc@gc.com",
  "nickname": "gc",
  "password": "gc",
  "confirmpwd": "gc",
  "checkcodekey": "1",
  "checkcode": "1"
}


###账号密码找回
POST {{auth_host}}/auth/findpassword
Content-Type: application/json

{
  "cellphone": "111111",
  "username": "gc",
  "email": "gc@gc.com",
  "nickname": "gc",
  "password": "gc",
  "confirmpwd": "gc",
  "checkcodekey": "1",
  "checkcode": "1"
}


###微信登录接口测试
POST {{auth_host}}/auth/wxLogin?code=1